internal: fixed C++11 compatibility of ConnectionIntrospector.cpp
boost::shared_ptr<T> cannot automatically be converted to a boolean return value:

rtt/rtt/internal/ConnectionIntrospector.cpp:335:12: error: cannot convert ‘RTT::internal::ConnectionIntrospector::NodePtr {aka boost::shared_ptr<RTT::internal::ConnectionIntrospector::Node>}’ to ‘bool’ in return
     return found;